/*
 * Local build identification tag for downstream forks.
 *
 * This file is intentionally not generated by autotools so that a fork can
 * carry a small, human-readable marker in `iperf3 -v` output without touching
 * the upstream version number/protocol fields.
 */
#ifndef IPERF3_LOCAL_BUILD_H
#define IPERF3_LOCAL_BUILD_H

/*
 * A short marker shown in version output.  Keep it stable and bump the
 * revision when making incompatible or significant downstream changes.
 */
#define IPERF3_LOCAL_VARIANT "lxchx r1"

#endif /* IPERF3_LOCAL_BUILD_H */
